config/routes.rb
Rails.application.routes.draw do
  get 'info/about'

  resources :images
  resources :digs do
    # resources :images
    resources :dig_participants, except: [:show]
    resources :announcements
    resources :artifacts do
      # resources :images
      collection do
        get "artifacts_by_category"
        get "artifacts_by_day"
      end
    end
  end

  resources :invitations, only: [:index, :create, :destroy]
  post "/invitations/:id/accept", to: "invitations#accept", as: "accept_invitation"

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :profiles, only: [:show]
  #static pages
  get "/about", to: "info#about", as: "about"
  get "/how-to-use", to: "info#how_to_use", as: "how_to_use"
  # Defines the root path route ("/")
  root "digs#index"
end

app/models/announcement.rb
# == Schema Information
#
# Table name: announcements
#
#  id         :integer          not null, primary key
#  body       :text
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  dig_id     :integer          not null
#  poster_id  :integer          not null
#
# Indexes
#
#  index_announcements_on_dig_id     (dig_id)
#  index_announcements_on_poster_id  (poster_id)
#
# Foreign Keys
#
#  dig_id     (dig_id => digs.id)
#  poster_id  (poster_id => users.id)
#
class Announcement < ApplicationRecord
  belongs_to :poster, class_name: "User", foreign_key: "poster_id"
  belongs_to :dig

  validates :title, presence: true
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: %i[ show edit update destroy ]
  before_action :set_dig
  before_action(except: [:new, :create]) { authorize(@announcement || Announcement) }

  # GET /announcements or /announcements.json
  def index
    @announcements = Announcement.where(:dig_id => @dig.id).order(created_at: :desc)
  end

  # GET /announcements/1 or /announcements/1.json
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
    @announcement.dig = @dig
    authorize @announcement
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements or /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)
    @announcement.dig = @dig
    authorize @announcement

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to dig_announcement_url(@dig, @announcement), notice: "Announcement was successfully created." }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1 or /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to dig_announcement_url(@dig, @announcement), notice: "Announcement was successfully updated." }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1 or /announcements/1.json
  def destroy
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to dig_announcements_url(@dig, @announcement), notice: "Announcement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def announcement_params
      params.require(:announcement).permit(:title, :body, :poster_id, :dig_id)
    end

    def set_dig
      @dig = Dig.find(params.fetch(:dig_id))
    end
end

app/views/announcements/_announcement.html.erb
<div id="<%= dom_id announcement %>">
  <h3>
    <%= announcement.title %>
  </h3>

  <div>
    <%= link_to "Back to dig", dig_path(@dig) %> |
    <%= link_to "Back to announcements", dig_announcements_path(@dig) %> 
  </div>

  <hr />

  <p>
    <%= announcement.body %>
  </p>

  <p>
    Posted on <%= announcement.created_at.strftime('%b %d, %Y') %> by <%= announcement.poster.first_name %> <%= announcement.poster.last_name %>
  </p>

</div>

app/views/announcements/_form.html.erb
<%= form_with(model: [@dig, announcement]) do |form| %>
  <% if announcement.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
        <% announcement.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.hidden_field :poster_id, value: current_user.id %>
    <%= form.hidden_field :dig_id, value: @dig.id %>
  </div>

  <div>
    <%= form.submit class: "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<h1>Editing announcement</h1>

  <div>
    <%= link_to "Back to announcement", dig_announcement_path(@dig, @announcement) %> |
    <%= link_to 'Back to dig', dig_path(@dig) %> |
    <%= link_to "Announcement list", dig_announcements_path(@dig, @announcement) %>
  </div>

  <hr>

<%= render "form", announcement: @announcement %>

app/views/announcements/index.html.erb
<h1>Announcements</h1>

<%= link_to "Back to dig", dig_path(@dig) %> |
<%= link_to "New announcement", new_dig_announcement_path(@dig) %>
<hr>

<div id="announcements">
  <% @announcements.each do |announcement| %>
    <div class="d-flex justify-content-between align-items-center row">
      <h3 class="col-md-3"><%= link_to "#{announcement.title}", dig_announcement_path(@dig, announcement) %></h3>
      <p class="col-md-3"><%= truncate(announcement.body, :length => 50, :separator => ' ') %></p>
      <% if announcement.poster == current_user %>
        <p class="col-md-3">Posted on <%= announcement.created_at.strftime('%b %d, %Y') %> by you</p>
      <% else %>
        <p class="col-md-3">Posted on <%= announcement.created_at.strftime('%b %d, %Y') %> by <%= announcement.poster.first_name %> <%= announcement.poster.last_name %></p>
      <% end %>
    </div>
    <hr>
  <% end %>
</div>

app/views/announcements/new.html.erb
<h1>New announcement</h1>
  <div>
    <%= link_to "Back to dig", dig_path(@dig) %> | 
    <%= link_to "Back to announcements", dig_announcements_path %>
  </div>

<hr />

<%= render "form", announcement: @announcement %>

app/views/announcements/show.html.erb
<%= render @announcement %>

<% if policy(@announcement).edit? && policy(@announcement).destroy? %>
  <div class="btn-toolbar">
    <%= link_to "Edit", edit_dig_announcement_path(@dig, @announcement), class: "btn btn-outline-primary button-margin" %>
    <%= button_to "Delete", dig_announcement_path(@dig, @announcement), method: :delete, class: "btn btn-outline-secondary" %>
  </div>
<% end %>