config/routes.rb
Rails.application.routes.draw do
  get 'info/about'

  resources :images
  resources :digs do
    # resources :images
    resources :dig_participants, except: [:show]
    resources :announcements
    resources :artifacts do
      # resources :images
      collection do
        get "artifacts_by_category"
        get "artifacts_by_day"
      end
    end
  end

  resources :invitations, only: [:index, :create, :destroy]
  post "/invitations/:id/accept", to: "invitations#accept", as: "accept_invitation"

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :profiles, only: [:show]
  #static pages
  get "/about", to: "info#about", as: "about"
  get "/how-to-use", to: "info#how_to_use", as: "how_to_use"
  # Defines the root path route ("/")
  root "digs#index"
end

app/models/dig.rb
# == Schema Information
#
# Table name: digs
#
#  id              :integer          not null, primary key
#  artifacts_count :integer          default(0)
#  description     :string
#  end_date        :date
#  location        :string
#  name            :string
#  season          :string
#  start_date      :date
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  creator_id      :integer          not null
#
# Indexes
#
#  index_digs_on_creator_id  (creator_id)
#
# Foreign Keys
#
#  creator_id  (creator_id => users.id)
#
class Dig < ApplicationRecord
  belongs_to :creator, class_name: "User"

  has_many :invitations, dependent: :destroy

  has_many :dig_participants, dependent: :destroy
  has_many :users, through: :dig_participants, source: :participant, dependent: :destroy
  has_many :leads, -> { where(dig_participants: { role: 'lead' }) }, through: :dig_participants, source: :participant, dependent: :destroy
  has_many :images, as: :imageable, dependent: :destroy
  has_many :artifacts, dependent: :destroy
  has_many :announcements, dependent: :destroy
  
  validates :name, presence: true

  before_create :set_season

  scope :led_by, ->(user_id) { joins(:dig_participants).where(dig_participants: { role: 'lead', participant_id: user_id }) }

  def self.ransackable_attributes(auth_object = nil)
    ["name", "season"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["dig_participants", "leads"]
  end

  def self.ransackable_scopes(auth_object = nil)
    [:led_by]
  end

  private

  def set_season
    # TODO: logic based on date/location to set season
  end

end

app/controllers/digs_controller.rb
class DigsController < ApplicationController
  before_action :set_dig, only: %i[ show edit update destroy ]
  before_action { authorize(@dig || Dig) }

  # GET /digs or /digs.json
  def index
    @q = current_user.digs.ransack(params[:q])
    @digs = @q.result(distinct: true)
  end

  # GET /digs/1 or /digs/1.json
  def show
  end

  # GET /digs/new
  def new
    @dig = Dig.new
  end

  # GET /digs/1/edit
  def edit
  end

  # POST /digs or /digs.json
  def create
    respond_to do |format|
      @dig = Dig.new(dig_params)
      if @dig.save
        format.html { redirect_to dig_url(@dig), notice: "Dig was successfully created." }
        format.json { render :show, status: :created, location: @dig }
        DigParticipant.create(dig_id: @dig.id, participant: current_user, role: "lead")
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @dig.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /digs/1 or /digs/1.json
  def update
    respond_to do |format|
      if @dig.update(dig_params)
        format.html { redirect_to dig_url(@dig), notice: "Dig was successfully updated." }
        format.json { render :show, status: :ok, location: @dig }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /digs/1 or /digs/1.json
  def destroy
    @dig.destroy

    respond_to do |format|
      format.html { redirect_to digs_url, notice: "Dig was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dig
      @dig = Dig.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dig_params
      params.require(:dig).permit(:start_date, :end_date, :location, :name, :description, :season, :artifact_count, :creator_id)
    end
end

app/views/digs/_card.html.erb
<div class="card mb-3 shadow-sm text-center">
  <div class="card-header">
    <h4 class="card-title pt-2"><%= dig.name %></h4>
  </div>
  <div class="card-body">
    <p class="card-text"><%= dig.location %></p>
    <p class="card-text"><%= dig.season %></p>
  </div>
</div>

app/views/digs/_dig.html.erb
<div id="<%= dom_id dig %>">

  <div class="mt-4 mb-4 d-flex justify-content-between align-items-center">
    <h1 class="text-danger">
      <%= dig.name %>
    </h1>
    <%= link_to "Announcements", dig_announcements_path(dig), class: "btn btn-secondary" %>
  </div>

  <hr />
  
  <%#= Great use of partials %>
  <%= link_to "Back to digs", digs_path %> 

  <hr />

  <p>
    <strong>Location:</strong>
    <%= dig.location %>
  </p>

  <p>
    <strong>Season:</strong>
    <%= dig.season %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= dig.start_date.strftime('%b %d, %Y') %> - <%= dig.end_date.strftime('%b %d, %Y') %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= dig.description %>
  </p>

  <p>
    <strong>Created by:</strong>
    <%= link_to "#{dig.creator.first_name} #{dig.creator.last_name}", profile_path(dig.creator) %>
  </p>

  <p>
    <strong>Your role in this dig is <%= dig.dig_participants.find_by(participant_id: current_user.id).role.humanize %>.</strong>

    <button type="button" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#rolesInfoModal">
      ?
    </button>

    <%= render partial: "shared/roles_info_modal" %>

  </p>

  <hr />

</div>

app/views/digs/_form.html.erb
<%= notice %>
<%= form_with(model: dig) do |form| %>
  <% if dig.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dig.errors.count, "error") %> prohibited this dig from being saved:</h2>

      <ul>
        <% dig.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location, class: "form-control" %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date, class: "form-control" %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.date_field :end_date, class: "form-control" %>
  </div>

  <div>
    <%= form.label :season, style: "display: block" %>
    <%= form.text_field :season, class: "form-control" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div>
    <%= form.hidden_field :creator_id, value: current_user.id %>
  </div>

  <div>
    <%= form.submit class: "btn btn-outline-secondary mt-2"%>
  </div>
<% end %>

app/views/digs/_search.html.erb
<div>
  <div id="filterForm" class="mb-2">
    <%= search_form_for @q do |f| %>
      <div class="form-check form-switch">
        <%= f.check_box :led_by, { class: "form-check-input", role: "switch" }, params.dig(:q, :led_by) || current_user.id, nil  %>
        <%= f.label :led_by, "Only show digs I lead", class: "form-check-label" %>
      </div>

      <div>
        <%= f.label :name_i_cont, "Filter by name", class: "form-label" %>
        <%= f.text_field :name_i_cont, :placeholder => "Enter a few characters", class: "form-control", type: "search" %>
      </div>

      <div>
        <%= link_to "Clear filters", digs_path(@dig) %>
        <%= f.submit :class => "btn btn-outline-secondary mt-2" %>
      </div>
    <% end %>
    <hr />
  </div>
</div>

app/views/digs/edit.html.erb
<h1>Editing dig</h1>

<div>
  <%= link_to "Back to dig", @dig %>
</div>

<hr />

<%= render "form", dig: @dig %>

app/views/digs/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <h1>Welcome, <%= current_user.first_name %>!</h1>
  <div>
    <%= link_to "Invitations", invitations_path, class: "btn btn-outline-secondary" %>
  </div>
</div>
<div class="text-center p-3">
  <h3><%= link_to "Create a new dig", new_dig_path, class: "btn btn-secondary btn-block col-lg-8 col-12" %></h3>
</div>
<div class="mb-4">
  <h3 class="text-center">Digs You Participate In</h3>
  <div>
    <% if current_user.digs.count != 0 %>
      <%= render "search" %>
        <% if @digs.count > 0 %>
          <div id="digs" class="row">
            <% @digs.order(end_date: :desc).each do |dig| %>
              <%= link_to dig_path(dig), class: "col-12" do %>
                <%= render "card", dig: dig %>
              <% end %>
            <% end %>
          </div>
        <% else %>
          <p class="text-center">No results</p>
        <% end %>
    <% else %>
      <p class="text-center">You're not participating in any digs. Create or join a dig to get started!<p>
    <% end %>
  </div>
</div>

app/views/digs/new.html.erb
<div>
  <%= link_to "Back to digs", digs_path %>
</div>

<hr />

<h1>New dig</h1>

<%= render "form", dig: @dig %>

app/views/digs/show.html.erb
<%= render @dig %>

<%= render "shared/images", parent: @dig %>

<hr />

<div>
  <h3>Participants</h3>
  <strong>This dig's lead(s):</strong>
  <% @dig.leads.each do |lead| %>
    <p><%= link_to "#{lead.first_name} #{lead.last_name}", profile_path(lead.id) %></p>
  <% end %>
  <i><%= link_to "Show all participants", dig_dig_participants_path(@dig) %></i>
</div>

<hr />

<div class="mb-3">
  <h3>Latest Artifacts</h3>
  <p><%= link_to "Log new artifact", new_dig_artifact_path(@dig), class: "btn btn-outline-secondary" %></p>
  <i><%= link_to "Show all (#{@dig.artifacts_count})", dig_artifacts_path(@dig) %></i>
</div>

<div>
  <% @dig.artifacts.order(created_at: :desc).limit(10).each do |artifact| %>
  <% if artifact.description.blank? && artifact.category.blank? %>
    <p>
      <%= link_to "Artifact ##{artifact.id}", dig_artifact_path(@dig, artifact) %>
    </p>
  <% elsif artifact.description.blank? %>
    <p>
      <%= link_to "Artifact ##{artifact.id} #{artifact.category}, #{artifact.material}", dig_artifact_path(@dig, artifact) %>
    </p>
  <% else %>
    <p>
      <%= link_to "Artifact ##{artifact.id} #{truncate(artifact.description, length: 50)}", dig_artifact_path(@dig, artifact) %>
    </p>
  <% end %>
<% end %>
</div>

<hr />

<% if policy(@dig).edit? && policy(@dig).destroy? %>
  <div class="btn-toolbar mt-2">
    <%= link_to "Edit this dig", edit_dig_path(@dig), class: "btn btn-outline-secondary button-margin" %>
    <%= button_to "Delete this dig", @dig, method: :delete, class: "btn btn-outline-danger", data: {turbo_confirm: 'Are you sure you want to delete this dig? This action is irreversible and will also delete all associated data.'} %>
  </div>
<% end %>