config/routes.rb
Rails.application.routes.draw do
  get 'info/about'

  resources :images
  resources :digs do
    # resources :images
    resources :dig_participants, except: [:show]
    resources :announcements
    resources :artifacts do
      # resources :images
      collection do
        get "artifacts_by_category"
        get "artifacts_by_day"
      end
    end
  end

  resources :invitations, only: [:index, :create, :destroy]
  post "/invitations/:id/accept", to: "invitations#accept", as: "accept_invitation"

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :profiles, only: [:show]
  #static pages
  get "/about", to: "info#about", as: "about"
  get "/how-to-use", to: "info#how_to_use", as: "how_to_use"
  # Defines the root path route ("/")
  root "digs#index"
end

app/views/shared/_cdn_assets.html.erb
<!-- Connect Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css">

<!-- Connect Bootstrap JavaScript and its dependencies -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"></script>

<!-- Connect Font Awesome -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js"></script>

app/views/shared/_flash.html.erb
<div class="row">
  <div class="col-md-12">
    <% if notice.present? %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_images.html.erb
<div>
  <strong><%= parent.class.name %> Images:</strong>
  <div class="overflow-auto mb-2 container-fluid">
    <div class="d-flex flex-nowrap">
    <% parent.images.each do |image| %>
      <% if image.image.present? %>
        <%= link_to image_path(image) do %>
          <%= image_tag image.image.url, class: "thumbnail button-margin" %>
        <% end %>
      <% else %>
        <p>There was a problem.</p>
      <% end %>
    <% end %>
    </div>
  </div>
  <% if parent.class == Dig %>
    <%= link_to "Add a new dig image", new_image_path(imageable_id: @dig.id, imageable_type: @dig.class.name), class: "btn btn-outline-secondary" %>
  <% elsif parent.class == Artifact %>
    <%= link_to "Add a new artifact image", new_image_path(imageable_id: @artifact.id, imageable_type: @artifact.class.name),  class: "btn btn-outline-secondary" %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Archaeo<span class="text-danger">Log</span></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "About us", info_about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "How to use ArchaeoLog", how_to_use_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Your profile", profile_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_roles_info_modal.html.erb
<div class="modal fade" id="rolesInfoModal" tabindex="-1" role="dialog" aria-labelledby="rolesInfoModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Roles</h5>
      </div>
      <div class="modal-body">
        <strong>Lead</strong>
        <p>A dig lead has full permissions within the dig. They can edit or delete the dig itself and view, edit, or delete artifacts and images. They can also add participants and change the roles of existing participants.</p>
                      
        <strong>Analyst</strong>
        <p>An analyst can view dig info, artifact details, images, and participants of digs they participate in. They are also able to view data visualizations. They can only edit or delete artifacts or images they have posted themselves.</p>

        <strong>Field Worker</strong>
        <p>Field workers can view dig info, artifact details, images, and participants of digs they participate in. They can only edit or delete artifacts or images they have posted themselves. This is the role best suited for students and is the most limited role.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>