config/routes.rb
Rails.application.routes.draw do
  get 'info/about'

  resources :images
  resources :digs do
    # resources :images
    resources :dig_participants, except: [:show]
    resources :announcements
    resources :artifacts do
      # resources :images
      collection do
        get "artifacts_by_category"
        get "artifacts_by_day"
      end
    end
  end

  resources :invitations, only: [:index, :create, :destroy]
  post "/invitations/:id/accept", to: "invitations#accept", as: "accept_invitation"

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :profiles, only: [:show]
  #static pages
  get "/about", to: "info#about", as: "about"
  get "/how-to-use", to: "info#how_to_use", as: "how_to_use"
  # Defines the root path route ("/")
  root "digs#index"
end

app/models/dig_participant.rb
# == Schema Information
#
# Table name: dig_participants
#
#  id             :integer          not null, primary key
#  role           :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  dig_id         :integer          not null
#  participant_id :integer          not null
#
# Indexes
#
#  index_dig_participants_on_dig_id                     (dig_id)
#  index_dig_participants_on_dig_id_and_participant_id  (dig_id,participant_id) UNIQUE
#  index_dig_participants_on_participant_id             (participant_id)
#
# Foreign Keys
#
#  dig_id          (dig_id => digs.id)
#  participant_id  (participant_id => users.id)
#
class DigParticipant < ApplicationRecord
  validates :participant_id, uniqueness: { scope: :dig_id, message: "User has already participated in this dig" }
  validates :role, presence: true

  belongs_to :dig
  belongs_to :participant, class_name: "User", foreign_key: "participant_id"

  scope :leads, -> { where(role: :lead) }

  enum role: {
    lead: 'lead',
    analyst: 'analyst',
    field_worker: 'field worker'
  }, _default: :field_worker

  def self.ransackable_attributes(auth_object = nil)
    ["participant_id", "role", "dig_id"]
  end

end

app/controllers/dig_participants_controller.rb
class DigParticipantsController < ApplicationController
  before_action :set_dig
  before_action :set_dig_participant, only: %i[ show edit update destroy ]
  before_action(except: [:new]) { authorize(@dig_participant || DigParticipant) }
  
  # GET /dig_participants or /dig_participants.json
  def index
    @dig_participants = DigParticipant.where(:dig_id => @dig.id)
  end

  # GET /dig_participants/1/edit
  def edit
  end

  # POST /dig_participants or /dig_participants.json
  def create
    dig_participant_params = params.require(:dig_participant).permit(:participant_email, :role)
    participant_email = dig_participant_params[:participant_email]
    participant = User.find_by(email: participant_email)
    respond_to do |format|
      if participant
        @dig_participant = @dig.dig_participants.new(dig_id: @dig.id, participant: participant, role: dig_participant_params[:role])
        if @dig_participant.save
          format.html { redirect_to dig_dig_participants_url(@dig), notice: "Dig participant was successfully added." }
          format.json { render :show, status: :created, location: @dig_participant }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @dig_participant.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to dig_url(@dig), status: :unprocessable_entity, notice: "User not found."}
        format.json { render json: { error: "User not found" }, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dig_participants/1 or /dig_participants/1.json
  def update
    respond_to do |format|
      if @dig_participant.update(dig_participant_params)
        format.html { redirect_to dig_dig_participants_url(@dig, @dig_participant), notice: "Dig participant was successfully updated." }
        format.json { render :show, status: :ok, location: @dig_participant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @dig_participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dig_participants/1 or /dig_participants/1.json
  def destroy
    @dig_participant.destroy

    respond_to do |format|
      format.html { redirect_to dig_dig_participants_url, notice: "Dig participant was successfully removed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dig_participant
      @dig_participant = DigParticipant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dig_participant_params
      params.require(:dig_participant).permit(:dig_id, :participant_id, :role)
    end

    def set_dig
      @dig = Dig.find_by(id: params.fetch(:dig_id))
    end
end

app/views/dig_participants/_dig_participant.html.erb
<div id="<%= dom_id dig_participant %>">

  <div class="d-flex align-items-center row">
    <h4 class="mt-0 mb-0 col-md-4">
      <%= link_to "#{dig_participant.participant.first_name} #{dig_participant.participant.last_name}", profile_path(dig_participant.participant_id) %>
    </h4>

    <div class="col-md-4 mt-2 mt-md-0 color-secondary">
      <strong>Role:</strong>
      <%= dig_participant.role.humanize %>
    </div>

    <div class="d-flex justify-content-md-end justify-content-between col-md-4 mt-2 mt-md-0 btn-toolbar">
      <% if @dig.leads.include? current_user && dig_participant.participant == current_user %>
        <%= link_to 'Edit role', edit_dig_dig_participant_path(@dig, dig_participant), class: "btn btn-outline-secondary button-margin" %>
        <%= button_to "Leave dig", dig_dig_participant_path(@dig, dig_participant), method: :delete, class: "btn btn-outline-danger",  data: {turbo_confirm: 'Are you sure you want to leave this dig? You will not be able to rejoin unless invited by a lead.'} %>
      <% elsif @dig.leads.include? current_user %>
        <%= link_to 'Edit role', edit_dig_dig_participant_path(@dig, dig_participant), class: "btn btn-outline-secondary button-margin" %>
        <%= button_to "Remove from dig", dig_dig_participant_path(@dig, dig_participant), method: :delete, class: "btn btn-outline-danger", data: {turbo_confirm: 'Are you sure you want to remove this user from the dig?'} %>
      <% elsif dig_participant.participant == current_user %>
        <%= button_to "Leave dig", dig_dig_participant_path(@dig, dig_participant), method: :delete, class: "btn btn-outline-danger",  data: {turbo_confirm: 'Are you sure you want to leave this dig? You will not be able to rejoin unless invited by a lead.'} %>
      <% end %>
    </div>
  </div>
</div>

app/views/dig_participants/_form.html.erb
<%= form_with(model: dig_participant, url: [@dig, @dig_participant]) do |form| %>
  <% if dig_participant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dig_participant.errors.count, "error") %> prohibited this dig_participant from being saved:</h2>

      <ul>
        <% dig_participant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.collection_select :role, DigParticipant.roles.keys, :to_s, :humanize, {}, class: "form-select" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dig_participants/_participant.html.erb
<div id="<%= dom_id dig_participant %>">

  <div class="d-flex align-items-center row">
    <h4 class="mt-0 mb-0 col-4">
      <%= link_to "#{dig_participant.participant.first_name} #{dig_participant.participant.last_name}", profile_path(dig_participant.participant_id) %>
    </h4>

    <div class="col-4">
      <strong>Role:</strong>
      <%= dig_participant.role.humanize %>
    </div>

    <div class="col-4 d-flex justify-content-end">
      <% if @dig.dig_participants.find_by(participant_id: current_user.id).role == "lead" %>
        <%= link_to 'Edit role', edit_dig_dig_participant_path(@dig, dig_participant) %>&nbsp;
        <%= button_to "Remove from dig", dig_dig_participant_path(@dig, dig_participant), method: :delete%>
      <% end %>
    </div>
  </div>
</div>

app/views/dig_participants/edit.html.erb
<h1>Editing dig participant</h1>

<div>
  <%= link_to "Back to dig participants", dig_dig_participants_path(@dig) %>
</div>

<hr />

<%= render "form", dig_participant: @dig_participant %>

app/views/dig_participants/index.html.erb
<h1><%= @dig.name %> participants</h1>

<div class="mt-4 mb-4 ml-4 d-flex justify-content-between">
  <div>
    <%= link_to "Back to dig", dig_path(@dig) %>
    <% if @dig.leads.include? current_user %> | 
      <span data-bs-toggle="modal" data-bs-target="#newInvitationModal" class="pointer">Invite new participant</span>
    <% end %>
  </div>
  <div>
    <button type="button" class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#rolesInfoModal">
      Understanding Roles
    </button>
  </div>
</div>

<div id="dig_participants">
  <%= render partial: "shared/roles_info_modal" %>
    <ul class="list-group">
      <% @dig_participants.each do |dig_participant| %>
        <li class="list-group-item pt-4 pb-4">
          <%= render dig_participant %>
        </li>
      <% end %>
    </ul>
</div>

<!-- MODAL -->
<div class="modal" id="newInvitationModal" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title text-danger">Invite Participant to <%=@dig.name%></h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <% @invitation = Invitation.new %>
        <%= render "invitations/form", invitation: @invitation %>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>